# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: AllenHsu
title: Algorithm Engineer
email: xuzhi0625@qq.com
# email_title: Email (Email title override)
phone: (+86)17610071006
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  allenhsu6
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: CSDN
  icon: fab fa-wordpress
  url: https://blog.csdn.net/allenhsu6
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    - I am passionate about developing advanced algorithms that tackle complex real-world challenges. With 6 years of experience in fields such as autonomous systems and AI-driven solutions, I have worked extensively across perception, decision-making, and control systems. My expertise lies in designing and optimizing models for object detection, classification, and predictive tasks, leveraging sensor data such as LiDAR, cameras, and other modalities. In addition to applied algorithm development, I have a strong background in crafting scalable deep learning models and reinforcement learning algorithms, focusing on robust performance and adaptability. I excel at bridging the gap between cutting-edge research and practical deployment, transforming state-of-the-art methodologies into efficient, real-world solutions. Beyond domain-specific applications, I am highly skilled in working with large-scale datasets and building end-to-end pipelines for training, validation, and evaluation. My programming expertise includes Python and C++, and I am well-versed in deep learning frameworks like PyTorch, enabling me to contribute to diverse AI-driven projects.

    - Collaboration and continuous learning are important aspects of my work. I thrive in dynamic and multidisciplinary teams, where I can contribute my technical expertise and learn from others. I am always eager to explore new technologies and stay updated with the latest advancements in the field of autonomous driving. I am excited about the opportunity to contribute my skills and knowledge to this world. I believe that my strong background in autonomous driving algorithms, combined with my passion for innovation, make me a valuable asset to any team working in this exciting field.

content:
        
  - title: Experience
    layout: list  
    content:

    - layout: left
        border: weak
        title: NIO Technology Autonomous Driving Large Model Division
        caption: August 2023 - Present
        sub_title: Senior Algorithm Engineer
        quote: > 
          Developed advanced algorithms for autonomous driving decision-making, perception, and data processing.
        description: |
          - OD Dataset Curation (August 2023 - May 2024)
            - Addressed the challenges of high annotation and training costs associated with millions of legacy data points and massive incremental datasets in object detection (OD) tasks.
            - Implemented active learning methods based on data gradient similarity to emphasize underlying reasoning process similarities and better utilize data distributions.
            - Achieved comparable accuracy to full dataset training using only 20% curated data, improving training efficiency by 5x and significantly reducing storage and computational costs.
            - Reduced annotation demand by 90% on incremental datasets, realizing a 10x efficiency improvement.
            - Developed a data quality inspection model to tackle common issues such as inaccurate bounding boxes and heading errors in auto-labeled production data.
            - Achieved precision of 92% and recall of 89% on noisy data identification using a fine-tuned evaluation dataset. The filtered OD model demonstrated a 1% overall performance improvement, with notable enhancements in close-range object detection.
            - Deployed the model on annotation production lines to proactively detect data defects, reducing manual inspection costs. This work resulted in two patents.

          - End-to-End Model Development (May 2024 - Present)
            - Pioneered the adaptation of vision-language multimodal large models for autonomous driving using the LLava-next framework.
            - Replaced the vision backbone with the DINOv2 base version and designed a 3D Q-Former to align visual and textual modalities.
            - Developed a custom VQA dataset to equip the model with 3D perception and reasoning capabilities. Integrated the VLM-based planner to handle complex scenarios, ensuring robustness and generalization for unknown cases. This work resulted in a patent.
            - Introduced diffusion models into trajectory planning for autonomous vehicles, inspired by their success in robotics.
            - Designed a transformer-based noise model with DDPM scheduling to predict 7-second future trajectories directly. The diffusion model ensures smooth, controllable, and natural multimodal predictions, outperforming discriminative models in long-horizon tasks.

      - layout: right
        border: weak
        title: ECARX Technology
        caption: March 2022 - Present
        sub_title: Senior Algorithm Engineer
        quote: > 
          Developed advanced algorithms for autonomous driving decision-making, perception, and data processing.
        description: |
          - Prediction Algorithm Module (March 2022 - October 2022)
            - Contributed as a core member in the development of the vehicle prediction module.
            - Developed the vehicle prediction module which takes inputs from obstacle fusion, lane fusion, ego vehicle localization, static object perception (high-definition maps), and previous planned trajectory.
            - Implemented obstacle prioritization, intent prediction, and trajectory prediction in the module.
            - Responsible for the development of the vehicle-side code, including pre- and post-processing of the models.
            - Handled data parsing, filtering, packaging, result validation, sorting, and deletion.
            - Implemented the integration of different model results based on different scenarios.
            
          - Parking Obstacle Perception Algorithm Module (Mass Production Project) (October 2022 - Present)
            - Core development member responsible for the 2D and 3D object detection model finetuning.
            - Adapted the related models for on-vehicle inference and aligned the inference accuracy with the PC-side.
            - Implemented post-processing for the 3D model.
            - Supported the visualization with DHU module for the central control screen and obstacle avoidance with the PNC module.
            
          - Data Closed-Loop Module (October 2022 - Present)
            - Module primarily serving the parking perception mass production project.
            - Led the module as the main responsible person.
            - Defined data acquisition requirements and tracked the establishment of the data acquisition platform and ground truth system.
            - Implemented the end-to-end automation of the data logging, filtering, automatic annotation, labeling, acceptance, and storage processes.
            - Leveraged the Speedup ground truth system to generate 3D object detection bounding boxes with centimeter-level accuracy.
            - Utilized GroundingDINO and SAM for text-to-2D box and segmentation outputs for large-scale and fast annotation data generation.
      
      - layout: left
        border: weak
        title: State Key Laboratory of Computer Science, Institute of Software, Chinese Academy of Sciences
        caption: March 2021 - February 2022
        sub_title: Algorithm Engineer
        quote: >
            Worked in the field of autonomous driving decision-making.
        description: |
          - Autonomous driving decision-making 
            - Conducted research on training vehicles to drive on highways and make correct decisions using deep reinforcement learning methods.
            - Traditional decision-making algorithms are typically based on rules and manual feature design, which often exhibit a conservative behavior to ensure safety. Utilized DQN (Deep Q-Network), one of the classic deep reinforcement learning algorithms, to make decisions based on the surrounding environment and ego vehicle information, aiming to maximize the expected reward.
            - Data engineering was primarily performed using open-source datasets and simulation environments.
            - Achieved an accuracy rate of over 91% in simulated testing, demonstrating the model's ability to make safe and reasonable decisions in high-speed scenarios.
          - Teaching assistant for the "Reinforcement Learning" course at the University of Chinese Academy of Sciences
            - Assisted in the development of course materials and experiments.
            - Covered topics such as Markov decision processes, Monte Carlo methods, temporal difference learning, eligibility traces, etc.
            - Designed unmanned vehicle simulation scenarios using the gym framework for implementing reinforcement learning methods like SARSA, Q-Learning, etc.
          - Collaboration with [Professor Zhang Lijun](https://iscasmc.ios.ac.cn/?page_id=148)

      - layout: right
        title: Waytous Intelligent Co., Ltd.
        caption: January 2020 - August 2020
        sub_title: Algorithm Engineer
        quote: > 
          Played a key role in the development and optimization of algorithms for path planning and control in autonomous systems.
        description: |
          - Worked on tasks related to the planning module.
            - Added the Jump Point Search algorithm to the algorithm library for global path planning in a freespace scenario in a certain mining area. In scenes with a high number of surrounding obstacles, this algorithm significantly improved search speed while still outputting the optimal path, compared to traditional A* algorithm.
            - Adapted the commonly used TEB (Timed Elastic Band) algorithm from ROS (Robot Operating System) to the trajectory optimization library for local trajectory planning.
          - Worked on data processing tasks, including constructing trajectory datasets for trajectory clustering, prediction, and other analysis tasks.
            - Utilized ETL (Extract, Transform, Load) techniques to process environment perception results from cameras and LiDAR (Light Detection and Ranging), as well as the positioning information from integrated inertial navigation systems.
            - Used the zarr library, which supports multiple data formats, to unify the data format and achieve fast data loading.
            - Uploaded the dataset to S3 for easy access and future algorithm iteration.    

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Open Source Project
        border: weak
        caption: December 2020 - February 2021
        quote: >
          Development of open-source tutorials related to ROS (Robot Operating System)
        description: |
          - Developed tutorials covering various aspects of ROS, including communication mechanisms such as topics and services.
          - Explored core functionality packages, such as the parameter server and TF (Transform) coordinate transformation.
          - Analyzed the hardware and software components of robot platforms, including modeling language URDF (Unified Robot Description Format), controllers, and the Gazebo simulator.
          - Provided detailed explanations of the ROS Navigation Stack, including nav_core, global_planner, local_planner, move_base, cost_map, AMCL (Adaptive Monte Carlo Localization), and more.
          - Published tutorials and corresponding code on platforms like [CSDN](https://blog.csdn.net/allenhsu6) and [GitHub](https://github.com/allenhsu6/LearnROS).
      - layout: left
        title: Visual Odometry
        border: weak
        caption: May 2019 - August 2019
        quote: >
          Work related to unmanned aerial vehicle (UAV) visual odometry
        description: |
          - Developed a visual odometry system for UAV localization.
          - Constructed local feature maps using keyframes and matched ORB feature points between each frame and the local map.
          - Used the PnP (Perspective-n-Point) algorithm to estimate the global pose.
          - Designed specifically for scenarios where only short-term motion needs to be considered, such as UAV control, with lower computational requirements compared to full-scale VSLAM systems while meeting the accuracy requirements of the application.

      - layout: left
        title: Formula Student Driverless Competition
        caption: August 2018 - December 2018
        quote: >
          Responsible for the planning and control of the Beijing University of Aeronautics and Astronautics (BUAA) AERO autonomous race car
        description: |
          - Led the planning and control division for the BUAA AERO autonomous race car in the China Formula Student Driverless Competition.
          - Managed tasks such as straight-line acceleration, figure-eight maneuvering, and high-speed trajectory following, with high requirements for speed and steering control.
          - Utilized PID control algorithms that have been widely validated in engineering applications due to their practicality.
          - Given the competition's focus on high dynamic response, the control module primarily used proportional and differential terms for accurate trajectory tracking, with less emphasis on steady-state error.

  - title: Education
    layout: list
    content:
      - layout: left       
        border: weak
        title: Sun Yat-Sen University
        caption: Ph.D. in Computer Science and Technology
        sub_title: 2020.08-2020.12
        description: |
          - Pursued a Ph.D. in Computer Science and Technology at Sun Yat-sen University, renowned for its academic excellence and research contributions.
          - Engaged in cutting-edge research projects related to SLAM and Perception algorithms.
          - Developed an in-depth understanding of advanced algorithms and their applications in the field of autonomous systems.
          - Although the program was discontinued due to personal circumstances, the short duration allowed for the acquisition of valuable knowledge and research skills.

      - layout: right
        border: weak
        title: Beihang University
        caption: M.Sc. in Control Science and Engineering
        sub_title: 2017.09-2020.01
        description: |
          - Successfully completed a rigorous Master's program in Control Science and Engineering at Beihang University, a renowned institution known for its excellence in engineering and technical education.
          - Engaged in cutting-edge research projects focused on autonomous systems, particularly in the field of planning and control with its applications.
          - Actively contributed to the academic community by publishing six scholarly papers in conferences and journals, showcasing expertise in areas such as control algorithms, motion planning, and autonomous navigation.
          - Collaborated with esteemed professors and fellow researchers, participating in research discussions, experimental design, and data analysis.
  
      - layout: left
        title: Northeastern University
        caption: B.Sc. in Automation
        sub_title: 2011.09-2015.07
        description: |
          - Earned a Bachelor's degree in Automation from Northeastern University.
          - Acquired a comprehensive understanding of automation principles and techniques.
          - Developed a solid foundation in programming, mathematics, and engineering fundamentals.
          - Successfully completed projects involving the design and implementation of control systems.


  - title: Skills
    layout: text
    content: |
      - Proficient in C++, Python, ROS, Linux, PyTorch, SQL, Shell, Git, Docker, MongoDB, TensorRT.
      - Familiar with autonomous driving algorithms, including reinforcement learning algorithms for prediction and decision-making modules, 2D detection, classification, and segmentation for perception vision modules, and 3D object detection.
      - Experienced in deploying algorithm models on different platforms, such as NVIDIA Xavier, Orin, BST A1000, and ECARX Antora1000.
      - Knowledgeable in sensors including cameras, lidars, INS (Inertial Navigation Systems), including basic principles, performance evaluation, comparative selection, spatial arrangement, time synchronization, and spatial calibration.
      - Proficient in the data closed-loop of autonomous driving, including data acquisition systems, ground truth systems, automated annotation, algorithm evaluation, shadow mode, data feedback, data mining, and data anonymization.
      - Hands-on experience in production projects.
      - English proficiency: CET 6; IELTS 6.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am an adventurous and free-spirited individual who finds joy in exploring new horizons. Passionate about rock music, I immerse myself in its powerful melodies and captivating rhythms. As an avid band enthusiast, I not only appreciate the artistry behind it but also enjoy actively participating in creating music. 

      Traveling on a shoestring budget is my preferred way to wander the world. I embrace the thrill of discovering hidden gems, immersing myself in diverse cultures, and forging unforgettable memories along the way. 

      Being a cinephile, I find solace and inspiration in the realm of cinema. From independent films to blockbuster hits, I am captivated by the art of storytelling and the magic of visual experiences. 

      My spirit is rebellious and unrestrained, always seeking freedom in expressing myself authentically. I cherish the value of individuality and embrace a lifestyle that encourages self-discovery and personal growth.

# Footer
footer_show_references: true
# references_title: 

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
